basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: support@fittrackplus.com
    name: FitTrack+ Team
    url: http://www.fittrackplus.com/support
  description: A comprehensive fitness platform API for gym members and trainers
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: FitTrack+ API
  version: "1.0"
paths:
  /health:
    get:
      consumes:
      - application/json
      description: Check if the API server is running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health Check
      tags:
      - Health
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
